fields:
# sheet: dnd5e-2024
  # row
    # col: col-12
  Name:
    label: "Name"
    input: string
  Category:
    label: "Category"
    input: select
    options:
      Epic Boon: Epic Boon
      Fighting Style: Fighting Style
      General: General
      Origin: Origin
      Other: Other
  Prerequisite:
    label: "Prerequisite"
    input: string
  Benefit:
    label: "Benefit"
    input: text
    rows: 3
  Repeatable:
    label: "Repeatable"
    input: checkbox
  ImageID:
    label: "Image ID"
    input: number
  Source:
    label: "Source"
    input: string
    # /col
  # /row
# /sheet