fields:
# sheet: dnd5e-2024
  # row
    # col: col-12
  Name:
    label: "Class"
    input: string
    placeholder: "eg. Barbarian"
    # /col
  # /row
  # row
    # col: col-12
      # table
  Primary Ability:
    label: "Primary Ability"
    input: select
    options:
      Strength: Strength
      Dexterity: Dexterity
      Constitution: Constitution
      Intelligence: Intelligence
      Wisdom: Wisdom
      Charisma: Charisma
  Hit Point Die:
    label: "Hit Point Die"
    input: string
    placeholder: "eg. 1D8 per level"
  Saving Throw Proficiencies:
    label: "Saving Throw Proficiencies"
    input: string
    placeholder: "eg. Strength and Constitution"
  Skill Proficiencies:
    label: "Skill Proficiencies"
    input: string
    placeholder: "eg. Choose 2: Animal Handling, Athletics, Intimidation, Nature, Perception, or Survival"
  Armor Training:
    label: "Armor Training"
    input: string
    placeholder: "eg. Simple and Martial weapons"
  Starting Equipment:
    label: "Starting Equipment"
    input: string
    placeholder: "eg. Choose A or B: (A) Greataxe, 4 Handaxes, Explorer’s Pack, and 15 GP; or (B) 75 GP"
      # /table
    # /col
  # /row
  # row
    # col: col-12
  Introduction:
    label: "Introduction"
    input: text
    rows: 3
  Becoming Level 1:
    label: "As a Level 1 Character:"
    input: text
    rows: 3
  text:
    label: "eg. Gain all the traits in the Core Barbarian Traits table. Gain the Barbarian’s level 1 features, which are listed in the Barbarian Features table."
  Becoming Multiclass:
    label: "As a Multiclass Character:"
    input: text
    rows: 3
  text:
    label: "eg. Gain the following traits from the Core Barbarian Traits table: Hit Point Die, proficiency with Martial weapons, and training with Shields. Gain the Barbarian’s level 1 features, which are listed in the Barbarian Features table."
  Class Features:
    label: "Class Features"
    input: text
    rows: 3
  Spells:
    label: "Spells"
    input: text
    rows: 3
  Details:
    label: "Details"
    input: text
    rows: 3
  Subclasses:
    label: "Subclasses"
    input: text
    rows: 3
    # /col
  # /row
# /sheet