fields:
# sheet: dnd5e-2024
  # row
    # col: col-12
  Name:
    label: "Name"
    input: string
  Level:
    label: "Level"
    input: select
    options:
      Cantrib: Cantrib
      1st : 1st
      2nd : 2nd
      3rd : 3rd
      4th : 4th
      5th : 5th
      6th : 6th
      7th : 7th
      8th : 8th
      9th : 9th
  Casting Time:
    label: "Casting Time"
    input: string
  RangeArea:
    label: "Range/Area"
    input: string
  Components:
    label: "Components"
    input: string
  Duration:
    label: "Duration"
    input: string
  School:
    label: "School"
    input: select
    options:
      Abjuration : Abjuration
      Alteration : Alteration
      Conjuration : Conjuration
      Divination : Divination
      Enchantment : Enchantment
      Illusion : Illusion
      Invocation : Invocation
      Necromancy : Necromancy
      Other: Other
  AttackSave:
    label: "Attack/Save"
    input: string
  DamageEffect:
    label: "Damage/Effect"
    input: string
  Description:
    label: "Description"
    input: text
    rows: 3
  HigherLevel:
    label: "At higher level"
    input: text
    rows: 3
  Available:
    label: "Available For"
    input: string
    placeholder: "Bard, Druid, ..."
  ImageID:
    label: "ImageID"
    input: integer
  Source:
    label: "Source"
    input: string
    # /col
  # /row
# /sheet